---
- hosts: loadbalance 
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
   - name: Disable SELinux
     selinux:
      state: disabled

   - name: add nginx-plus repo
     yum_repository:
      name: nginx-plus
      description: nginx-plus repo
      baseurl: http://10.4.150.213/nginx-rpms
      gpgcheck: no
      enabled: yes

   - name: Install packages
     yum:
      name:
       - epel-release
       - "@Development tools"
       - git
       - nginx-plus 
      state: latest
    
   - name: upgrade all packages
     yum:
      name: '*'
      state: latest
     
   - name: started and enabled nginx
     service:
      name: nginx
      state: started
      enabled: yes
  
   - name: remove older Nginx Config
     file:
      path: /etc/nginx
      state: absent
    
   - name: clone new Nginx config
     git:
      repo: https://github.com/MAELUP/loadbalance-dev.git
      dest: /etc/nginx
    
   - name: restart nginx
     service:
      name:  nginx
      state: restarted

   - name: open service port_80
     firewalld:
      port: 80/tcp
      state: enabled
      permanent: yes
      immediate: yes

   - name: open service port_443
     firewalld:
      port: 443/tcp
      permanent: yes
      state: enabled
      immediate: yes



