---
- hosts: apigateway 
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
   - name: Disable SELinux
     selinux:
      state: disabled 

   - name: Update /etc/hosts from inventory
     lineinfile: 
      dest: /etc/hosts 
      regexp: '.*{{item}}$' 
      line: '{{ hostvars[item].ansible_default_ipv4.address }}   {{ hostvars[item].ansible_nodename }}'
      state: present
      unsafe_writes: yes
     with_items: '{{ groups.apigateway }}'
   
   - name: restart network 
     service:
       name: network
       state: restarted   

   - name: open service port_80
     firewalld:
      port: '{{ item.port }}'
      permanent: yes
      state: enabled
      immediate: yes
     with_items:
      - { port: '80/tcp' } 
      - { port: '8080/tcp' }
      - { port: '8081/tcp' }
      - { port: '443/tcp' }
      - { port: '9999/tcp' }

  

 
