---
- hosts: apigateway 
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
   - name: Disable SELinux
     selinux:
      state: disabled

   - name: add nginx-plus repo
     yum_repository:
      name: nginx-plus
      description: nginx-plus repo
      baseurl: http://10.4.150.213/nginx-rpms
      gpgcheck: no
      enabled: yes

   - name: Install packages
     yum:
      name:
       - "@Development tools"
       - git
       - nginx-plus
       - nginx-plus-module-modsecurity
       - nginx-ha-keepalived
      state: present

   - name: upgrade all packages
     yum:
      name: '*'
      state: latest
     
   - name: started and enabled nginx
     service:
      name: nginx
      state: started
      enabled: yes
  
   - name: remove older Nginx Config
     file:
      path: /etc/nginx
      state: absent

   - name: clone new Nginx config
     git:
      repo: https://github.com/MAELUP/apigateway-dev.git
      dest: /etc/nginx
    
   - name: Change file ownership, group and permissions
     file:
      path: /etc/nginx
      owner: nginx
      group: nginx
      mode: '0755' 

   - name: Update /etc/hosts from inventory
     lineinfile:
      dest: /etc/hosts
      regexp: '.*{{item}}$'
      line: '{{ hostvars[item].ansible_default_ipv4.address }}   {{ hostvars[item].ansible_nodename }}'
      state: present
      unsafe_writes: yes
     with_items: '{{ groups.apigateway }}'
   
   - name: add virtual ip to /etc/hosts
     lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ virtual_node_ipaddress }}$'
      line: '{{ virtual_node_ipaddress }}   apigateway.service'
      state: present
      unsafe_writes: yes
   
   - name: restart network
     service:
      name: network
      state: restarted
 
   - name: restart nginx
     service:
      name:  nginx
      state: restarted

   - name: open service port_80
     firewalld:
      port: 80/tcp
      state: enabled
      permanent: yes
      immediate: yes

   - name: open service port_8081
     firewalld:
      port: 8081/tcp
      permanent: yes
      state: enabled
      immediate: yes

   - name: open service port_8080
     firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
      immediate: yes

   - name: add template master 
     template: 
      src: keepalived.mas.conf.j2 
      dest: /etc/keepalived/keepalived.conf 
     when: inventory_hostname in groups['apigateway-master']

   - name: add template backend
     template:
      src: keepalived.bak.conf.j2
      dest: /etc/keepalived/keepalived.conf 
     when: inventory_hostname in groups['apigateway-backup']   

   - name: Start keepalived
     service: 
      name: keepalived 
      state: started
      enabled: yes

   - name: Configurar configuració de keepalived
     template: 
      src: keepalived.mas.conf.j2 
      dest: /etc/keepalived/keepalived.conf

   - name: restarted keepalived
     service: 
      name: keepalived 
      state: restarted
