---
- hosts: apigateway 
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
   - name: Disable SELinux
     selinux:
      state: disabled

   - name: add nginx-plus repo
     yum_repository:
      name: nginx-plus
      description: nginx-plus repo
      baseurl: http://10.4.150.213/nginx-rpms
      gpgcheck: no
      enabled: yes

   - name: Install packages
     yum:
      name:
       - "@Development tools"
       - git
       - nginx-plus
       - nginx-plus-module-modsecurity
      state: present

   - name: upgrade all packages
     yum:
      name: '*'
      state: latest
     
   - name: started and enabled nginx
     service:
      name: nginx
      state: started
      enabled: yes
  
   - name: remove older Nginx Config
     file:
      path: /etc/nginx
      state: absent
    
 
 #  - name: remove older Nginx Config
 #    file:
 #     path: "{{ item.path }}"
 #     state: absent
 #    with_items: 
 #     - { path: '/etc/nginx/conf.d' }
 #     - { path: '/etc/nginx/nginx.conf'}
 # 
 #  - name: clone new Nginx config
 #    git:
 #     repo: https://github.com/MAELUP/apigateway-dev.git
 #     dest: /var/www
   
 #  - name: add new Nginx Config
 #    copy: 
 #     src: "{{ item.path_src }}"
 #     dest: "{{ item.path_dest }}"
 #     remote_src: yes 
 #     directory_mode: "{{ item.isDir }}"
 #    with_items: 
 #     - { path_src: '/var/www/api_backends.conf', path_dest: '/etc/nginx/api_backends.conf', isDir: 'no' }
 #     - { path_src: '/var/www/api_gateway.conf', path_dest: '/etc/nginx/api_gateway.conf', isDir: 'no' }
 #     - { path_src: '/var/www/api_json_errors.conf', path_dest: '/etc/nginx/api_json_errors.conf', isDir: 'no' }
 #     - { path_src: '/var/www/api_keys.conf', path_dest: '/etc/nginx/api_keys.conf', isDir: 'no' }
 #     - { path_src: '/var/www/nginx.conf', path_dest: '/etc/nginx/nginx.conf', isDir: 'no' }
 #     - { path_src: '/var/www/api_conf.d', path_dest: '/etc/nginx/', isDir: 'yes' }
 #     - { path_src: '/var/www/conf.d', path_dest: '/etc/nginx/', isDir: 'yes' }
   

   - name: clone new Nginx config
     git:
      repo: https://github.com/MAELUP/apigateway-dev.git
      dest: /etc/nginx
    
   - name: Change file ownership, group and permissions
     file:
      path: /etc/nginx
      owner: nginx
      group: nginx
      mode: '0755' 
       
 #  - name: clear file 
 #    file:
 #     path: /var/www 
 #     state: absent

   - name: restart nginx
     service:
      name:  nginx
      state: restarted

   - name: open service port_80
     firewalld:
      port: 80/tcp
      state: enabled
      permanent: yes
      immediate: yes

   - name: open service port_8081
     firewalld:
      port: 8081/tcp
      permanent: yes
      state: enabled
      immediate: yes

   - name: open service port_8080
     firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
      immediate: yes


